### ISSUE TITLE
Liturgy of the Bell

### ISSUE THREAD

**Issue by kaedys** [yomishino/FFXIVActionEffectRange#10]
The AoE range displayed for Liturgy of the Bell, when placed, is only about a 1 yalm circle, when the heal effect range on it is 20 yalms from the placement point.  Could this be updated to show the heal effect range of 20y instead?  Also, not sure if this is feasible, but it'd be handy if it could show the AoE effect range again, as a visual cue that it occurred, when one of the charges is expended or it expires/ends early (probably as an option, not sure if everyone would want that, but it'd certainly help me).

**Comment by yomishino** [comment]
Update: b9d37feb47cf6f21c75b9342eeb9505ea94321c8
Now it will show the effect range as 20y when you first use the skill (for placement) and manually use the skill to consume all the remaining stacks.

It will not show any effect range hint right now if the effect is not triggered by player actions. This affects a few skills including Liturgy of the Bell. The feature will require a bit more work to keep track of additional stuff, or perhaps rewrite the logic, for which I have some ideas but will not work on it soon (or perhaps will only work on it very slowly).

Since the latter one is not an issue about Liturgy of the Bell I am closing this issue for now.

**Comment by kaedys** [comment]
Alrighty, much appreciated!
