### ISSUE TITLE
Showing effect range during casting

### ISSUE THREAD

**Issue by Battler624** [yomishino/FFXIVActionEffectRange#3]
Been searching through the plugins and found this, very lovely, I would honestly just change the defaults a bit, Here is what I settled with. 
![image](https://user-images.githubusercontent.com/9511158/155866699-87fbd899-8632-480a-b185-cdbc1898cc20.png)

I remember a chinese addon doing the same as this but cant find it for the life of me.

I'm wondering if you can add pre-emptive circles? so I can get inrange of a medica 2 for example.

**Comment by Battler624** [comment]
Oh yea, Json not working, built it myself.

**Comment by yomishino** [comment]
Thank you, I'm glad you like it.

Just to be sure, by "pre-emptive" do you mean during casting, for example? It could be quite useful, although there're some non-technical considerations that make me a little hesitated though. By design this plugin only intends to enhance the visual aspect of the action effect already available in game, while this new feature would slightly go beyond that. Perhaps I'll think about it a bit.

**Comment by Battler624** [comment]
It is as you say, id love it if it was shown during casting.

**Comment by yomishino** [comment]
d2ef5ef2ee814e6dad033194cf4c8ea226dabb9f
